apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "migration-helm.fullname" . }}-flyway-baseline"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 {{ .Values.postgresql.auth.host }} {{ .Values.postgresql.service.port }}; do echo waiting for postgres; sleep 1; done']
      containers:
        - name: flyway
          image: flyway/flyway:latest
          env:
            - name: FLYWAY_URL
              value: jdbc:postgresql://{{ .Values.postgresql.auth.host }}:{{ .Values.postgresql.service.port }}/{{ .Values.postgresql.auth.database }}
            - name: FLYWAY_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: FLYWAY_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
          args: ["baseline"]
      restartPolicy: OnFailure
