apiVersion: v1
kind: ConfigMap
metadata:
  name: migrate-flyway
data:
  # V1__Baseline.sql: |
  #   CREATE TABLE person (
  #       id SERIAL PRIMARY KEY,
  #       name VARCHAR(100)
  #   );
  V2__Add_Into_Persons.sql: |
    INSERT INTO person (name) VALUES ('Ding Dong');


  V3__Add_new_table.sql: |
    CREATE TABLE orders (
        id SERIAL PRIMARY KEY,
        order_number VARCHAR(50),
        order_date DATE
    );
