apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migrate
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: flyway/flyway:latest
          command: ["flyway", "-url=jdbc:postgresql://postgres:5432/mydatabase", "-user=root", "-password=asd123", "migrate"]
          volumeMounts:
            - name: flyway-sql
              mountPath: /flyway/sql
      restartPolicy: OnFailure
      volumes:
        - name: flyway-sql
          configMap:
            name: migrate-flyway
